language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-human-pose-estimator .
  - docker run -it -d -p 5000:5000 max-human-pose-estimator
  - sleep 30
before_script:
  - pip install flake8 pytest requests
script:
  - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
  - pytest tests/test.py
